### PR TITLE
replace 1:ncol with seq_len(ncol) to avoid problems with 0-width matr…

### PR DESCRIPTION
**Pull request by byandell**
…ices

Karl,
If there any of the matrices going into scan1coef_names have 0 columns, then present code generates 2 bogus column names with 1:0; better to use seq_len
Brian

### CODE REVIEW

**Comment by byandell** [comment]
Added another edit to fit1.R to create 0-col version of genoprobs if NULL provided.

**Comment by kbroman** [comment]
I think if we leave genoprobs off, we actually need to make it a column of ones. I'll fix it.

**Comment by kbroman** [comment]
Actually, it's looking to me like excluding the genoprobs isn't terribly useful. 

The LOD scores are such that its QTL+covar vs covar. So if you leave out the QTL or make them a column of 1s, the LOD scores are all strictly 0. 

What exactly are you trying to do?

**Comment by byandell** [comment]
Karl,
Right. My bad. See last email to you. Please back out of these changes.
Brian

**Comment by kbroman** [comment]
No worries. Allowed me to test my understanding of `git revert`.

**Pull request merged**
